MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './jx_vit_base_p16_384-83fb41ba.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'

  NO_MARGIN: True
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  JPM: False
  SHIFT_NUM: 8
  RE_ARRANGE: False


INPUT:
  SIZE_TRAIN: [ 256, 256 ]
  SIZE_TEST: [ 256, 256 ]
  PROB: 0.0
  RE_PROB: 0.0
  RO_DEGREE: 15
  BRIGHT_PROB: 0.5
  SATURA_PROB: 0.0
  CONTRAST_PROB: 0.5
  HUE_PROB: 0.0
  PADDING: 10
  PIXEL_MEAN:  [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('ATRW')
  ROOT_DIR: ('./ATRW')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 150
  BASE_LR: 0.01
  IMS_PER_BATCH: 32
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 150
  LOG_PERIOD: 10
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: './transformer.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './log/ATRW'