MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/data1/lcy_log/save/resnet50-19c8e357.pth'
#  resnet50-19c8e357.pth:
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'resnet50'
  #resnet50
  NO_MARGIN: True
#  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
#  DIST_TRAIN: True
  JPM: True
  SHIFT_NUM: 8
  RE_ARRANGE: False

INPUT:
  SIZE_TRAIN: [ 256, 256 ]   #[256, 256]
  SIZE_TEST: [ 256, 256 ]
  PROB: 0.0 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  RO_DEGREE: 10
  BRIGHT_PROB: 0.2
  SATURA_PROB: 0.2
  CONTRAST_PROB: 0.2
  HUE_PROB: 0.2
  PADDING: 10
  PIXEL_MEAN:  [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('seal')
  ROOT_DIR: ('/data0/lichenyue_data/seal/')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 150
  BASE_LR: 0.001
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 150
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: '/data1/lcy_log/seal/transformer_150.pth'
  NECK_FEAT: 'after'
# after
  FEAT_NORM: 'yes'

OUTPUT_DIR: '/data1/lcy_log/seal'
#OUTPUT_DIR: '/home/lichenyue/TransReID-main1/TransReID-main1/logs/ATRW_vit_transreid_single'


